[server]
host = "0.0.0.0"
port = 8081
workers = 16

[radio]
device_index = 0
center_freq = 156_450_000
sample_rate = 250_000
tuner_gain = 10

[misc]
transcribe_model = "tiny_en.bin"
data_dir = "data"

[[channels]]
name = "Marine 9"
freq = 156_450_000
squelch = 0.01
gain = 10.0
